services:
  posgresql:
    image: postgres:latest
    container_name: library_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: library_db
    ports:
      - 5432:5432

