apiVersion: v1
kind: ConfigMap
metadata:
  name: library-config
  namespace: library
data:
  application.yml: |
    server:
      port: ${SERVER_PORT:8000}
      shutdown: graceful

    spring:
      application:
        name: library
      liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml
      datasource:
        url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:library_db}
        username: ${DB_USERNAME:admin}
        password: ${DB_PASSWORD:admin@123}
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: ${JPA_DDL_AUTO:update}
        show-sql: ${SHOW_SQL:true}
        properties:
          hibernate:
            format_sql: ${FORMAT_SQL:true}

    management:
      endpoints:
        enabled-by-defalut: false
        web:
          exposure:
            include: health
      endpoint:
        health:
          enabled: true
          probes:
            enabled: true
      health:
        defaults:
          enabled: false

    google:
      books:
        api:
          key: ${GOOGLE_API_KEY:}
